devices:
    selector_position_map:
        module: builtins
        class: dict
        kwds:
            CLEAR: 5
            YELLOW: 4
            sbip: 3
            OUTLET: 2
            AMBIENT: 1
    selector_serial_port:
        module: serial
        class: Serial
        args:
        - "/dev/serial/by-path/platform-xhci-hcd.0-usb-0:1.3:1.0-port0"
        kwds:
            baudrate: 9600
    selector:
        module: vicivalve
        class: VICI
        kwds:
            serial: selector_serial_port
            positions: 10
            position_map: selector_position_map
    source_pump:
        module: runze_control.syringe_pump
        class: MiniSY04
        kwds:
            com_port: "/dev/serial/by-path/platform-xhci-hcd.0-usb-0:1.2:1.0-port0"
            address: 0x00
            syringe_volume_ul: 20000
    reaction_vessel:
        module: brainwasher.devices.reaction_vessel
        class: ReactionVessel
        kwds:
            curr_volume_ul: 0
            max_volume_ul: 10000
            name: reaction-vessel
    mixer:
        module: brainwasher.devices.sequent_microsystems.mixer
        class: PWMMixer
        kwds:
            board_address: 2
            channel: 7
            max_rpm: 1000
    pressure_sensor:
        module: brainwasher.devices.sequent_microsystems.pressure_sensor
        class: PX409030A5V
        kwds:
            stack: 0
            i2c_bus: 1
            channel: 1
            min_voltage: 0.004
            max_voltage: 5.010
    rv_source_valve:
        module: brainwasher.devices.sequent_microsystems.valve
        class: ThreeTwoValve
        kwds:
            name: rv_source
            board_address: 2
            channel: 2
    rv_exhaust_valve:
        module: brainwasher.devices.sequent_microsystems.valve
        class: ThreeTwoValve
        kwds:
            name: rv_exhaust
            board_address: 2
            channel: 1
    drain_exhaust_valve:
        module: brainwasher.devices.sequent_microsystems.valve
        class: NCValve
        kwds:
            name: drain_exhaust
            board_address: 2
            channel: 3
    drain_waste_valve:
        module: brainwasher.devices.sequent_microsystems.valve
        class: NCValve
        kwds:
            name: drain_waste
            board_address: 2
            channel: 4
    selector_lds_map:
        module: builtins
        class: dict
        kwds:
            CLEAR: selector_clear_bds
            YELLOW: selector_yellow_bds
            sbip: selector_sbip_bds
            AMBIENT: selector_ambient_bds
# Liquid Detection Sensors
    pump_bds:
        module: brainwasher.devices.sequent_microsystems.liquid_presence_detection
        class: BubbleDetectionSensor
        kwds:
            board_address: 0
            channel: 11
    waste_pump_bds:
        module: brainwasher.devices.sequent_microsystems.liquid_presence_detection
        class: BubbleDetectionSensor
        kwds:
            board_address: 0
            channel: 12
    selector_clear_bds:
        module: brainwasher.devices.sequent_microsystems.liquid_presence_detection
        class: BubbleDetectionSensor
        kwds:
            board_address: 0
            channel: 5
    selector_yellow_bds:
        module: brainwasher.devices.sequent_microsystems.liquid_presence_detection
        class: BubbleDetectionSensor
        kwds:
            board_address: 0
            channel: 4
    selector_sbip_bds:
        module: brainwasher.devices.sequent_microsystems.liquid_presence_detection
        class: BubbleDetectionSensor
        kwds:
            board_address: 0
            channel: 3
    selector_ambient_bds:
        module: brainwasher.devices.sequent_microsystems.liquid_presence_detection
        class: BubbleDetectionSensor
        kwds:
            board_address: 0
            channel: 10
#    vessel_cam:
#        module: brainwasher.devices.raspberry_pi.camera
#        class: Camera
#        args:
#        - 0
#        kwds:
#            name: "braincam"
# Full System:
    flow_chamber:
        module: brainwasher.proof_of_concept
        class: FlowChamber
        kwds:
            selector: selector
            selector_lds_map: selector_lds_map
            pump: source_pump
            pressure_sensor: pressure_sensor
            mixer: mixer
            reaction_vessel: reaction_vessel
            rv_source_valve: rv_source_valve
            rv_exhaust_valve: rv_exhaust_valve
            drain_exhaust_valve: drain_exhaust_valve
            drain_waste_valve: drain_waste_valve
            pump_prime_lds: pump_bds
