logging:
    version: 1
    disable_existing_loggers: true
    formatters:
        standard:
            format: '%(asctime)s:%(name)s:%(levelname)s: %(message)s'
        colored:
            (): coloredlogs.ColoredFormatter
            format: '%(asctime)s:%(name)s:%(levelname)s: %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S.%f'
            field_styles:
                asctime:
                    color: green
                hostname:
                    color: blue
                levelname:
                    #bold: true
                    bright: true
                    color: magenta
                name:
                    color: cyan
                programname:
                    color: cyan
                username:
                    color: yellow
        log_server:
            format: '%(asctime)s\n%(name)s\n%(levelname)s\n%(funcName)s (%(filename)s:%(lineno)d)\n%(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            level: DEBUG
            formatter: colored
            class: logging.StreamHandler
            stream: ext://sys.stdout
        file:
            level: DEBUG
            formatter: standard
            class: logging.FileHandler
            mode: 'a'
            filename: logs.log
        web_handler:
            level: INFO
            formatter: log_server
            host: eng-logtools.corp.alleninstitute.org
            port: 9000
            class: logging.handlers.SocketHandler
    loggers:
        '':
            level: DEBUG
            handlers:
            - console
            - file
            #- web_handler
devices:
    selector_port_map:
        class: builtins.dict
        kwds:
            clear: 5
            pbs: 4
            sbip: 3
            outlet: 2
            ambient: 1
    selector:
        class: brainwasher.devices.simulated_devices.selector.SimCloseableSelector
        kwds:
            port_count: 10
            port_map: selector_port_map
    source_pump:
        class: brainwasher.devices.simulated_devices.syringe_pump.SimSyringePump
        kwds:
            syringe_volume_ul: 20000
    reaction_vessel:
        class: brainwasher.devices.vessels.ReactionVessel
        skip_kwds: [name]
        kwds:
            name: reaction_vessel
            max_volume_ul: 10000
    waste_vessels:
        factory: device_spinner.builtins.to_list
        args:
            - thf_waste_vessel
            - aqueous_waste_vessel
    thf_waste_vessel:
        class: brainwasher.devices.vessels.WasteVessel
        skip_kwds: [name]
        kwds:
            name: thf_waste_vessel
            max_volume_ul: 250000
            compatible_chemicals: !!set {"thf", "deionized_water"}
    aqueous_waste_vessel:
        class: brainwasher.devices.vessels.WasteVessel
        skip_kwds: [name]
        kwds:
            name: aqueous_waste_vessel
            max_volume_ul: 250000
            compatible_chemicals: !!set {"sbip", "deionized_water", "pbs"}
    mixer:
        class: brainwasher.devices.mixer.SimulatedMixer
        kwds:
            max_rpm: 1200
    pressure_sensor:
        class: brainwasher.devices.simulated_devices.pressure_sensor.SimPressureSensor
    rv_source_valve:
        class: brainwasher.devices.valves.valve.ThreeTwoSolenoidValve
        kwds:
            name: rv_source
    rv_exhaust_valve:
        class: brainwasher.devices.valves.valve.ThreeTwoSolenoidValve
        kwds:
            name: rv_exhaust
    output_bypass_valves:
        factory: device_spinner.builtins.to_list
        args:
            - thf_output_bypass_valve
            - aqueous_output_bypass_valve
    thf_output_bypass_valve:
        class: brainwasher.devices.valves.valve.NCSolenoidValve
        kwds:
            name: output_bypass
    aqueous_output_bypass_valve:
        class: brainwasher.devices.valves.valve.NCSolenoidValve
        kwds:
            name: aqueous_output_bypass
    waste_drain_valves:
        factory: device_spinner.builtins.to_list
        args:
            - thf_waste_drain_valve
            - aqueous_waste_drain_valve
    thf_waste_drain_valve:
        class: brainwasher.devices.valves.valve.NCSolenoidValve
        kwds:
            name: thf_waste_drain
    aqueous_waste_drain_valve:
        class: brainwasher.devices.valves.valve.NCSolenoidValve
        kwds:
            name: aqueous_waste_drain
    selector_lds_map:
        class: builtins.dict
        kwds:
            clear: selector_clear_bds
            pbs: selector_pbs_bds
            sbip: selector_sbip_bds
            ambient: selector_ambient_bds
# Liquid Detection Sensors
    pump_bds:
        class: brainwasher.devices.liquid_presence_detection.BubbleDetectionSensor
    waste_pump_bds:
        class: brainwasher.devices.liquid_presence_detection.BubbleDetectionSensor
    selector_clear_bds:
        class: brainwasher.devices.liquid_presence_detection.BubbleDetectionSensor
    selector_pbs_bds:
        class: brainwasher.devices.liquid_presence_detection.BubbleDetectionSensor
    selector_sbip_bds:
        class: brainwasher.devices.liquid_presence_detection.BubbleDetectionSensor
    selector_ambient_bds:
        class: brainwasher.devices.liquid_presence_detection.BubbleDetectionSensor
# Full System:
    brainwasher:
        class: brainwasher.devices.instruments.brainwasher.BrainWasher
        kwds:
            selector: selector
            selector_lds_map: selector_lds_map
            pump: source_pump
            pressure_sensor: pressure_sensor
            mixer: mixer
            reaction_vessel: reaction_vessel
            waste_vessels: waste_vessels
            rv_source_valve: rv_source_valve
            rv_exhaust_valve: rv_exhaust_valve
            output_bypass_valves: output_bypass_valves
            waste_drain_valves: waste_drain_valves
            pump_prime_lds: pump_bds
