router_server_api:
  named_calls:
    seqflow_start:
      obj_name: "seqflow"
      attr_name: "start_run"
    seqflow_pause:
      obj_name: "seqflow"
      attr_name: "pause"
    seqflow_get_job:
      obj_name: "seqflow"
      attr_name: "get_job"
    seqflow_set_job:
      obj_name: "seqflow"
      attr_name: "set_job"
    seqflow_get_config:
      obj_name: "seqflow"
      attr_name: "get_config"
  periodic_streams:
    seqflow_get_progress:
      frequency_hz: 1
      obj_name: "seqflow"
      attr_name: "get_progress"
router_server_kwargs:
    rpc_port: 5557
    broadcast_port: 5558
devices:
  selector_port_map:
    class: builtins.dict
    kwds:
      incorporation_buffer: 1
      pbst: 2
      iodoacetamide_blocker: 3
      irm: 4
      usm: 5
      crm: 6
      fish_wash: 7
      strip: 8
      hyb_oligos_mix: 9
      dapi: 10
      bc_primer_mix: 11
      gene_primer_mix: 12
      hyb_oligos_mix_2: 13
      end: 14
      hyb_oligos_mix_3: 15
      hyb_oligos_mix_4: 16
  config:
    class: seqflow.seqflow_config_model.SeqFlowConfig
    kwds:
      instrument_name: "Default SeqFlow"
  pump:
    class: mixology.devices.pump.ismatec_peristaltic_pump.IsmatecPeristalticPumpDevice
    kwds:
        name: "IsmatecPumpDevice_1"
        port: "COM4"
        baudrate: 115200
        tubing_diameter: 0.51
        tubing_yield: 0.017
        max_rpm: 160
        min_rpm: 0.2
        pump_id: "1"
        flow_reversed: 0
  sub_selector_1:
    class: mixology.devices.selector.selector.SerialSelector
    kwds:
      name: "ElveflowSelector_1"
      port: "COM6"
      baudrate: 9600
  sub_selector_2:
    class: mixology.devices.selector.selector.SerialSelector
    kwds:
      name: "ElveflowSelector_2"
      port: "COM5"
      baudrate: 9600
  sub_selector_list:
    factory: device_spinner.factory_utils.to_list
    args:
      - sub_selector_1
      - sub_selector_2
  selector:
    class: mixology.devices.selector.mux.CascadedMux
    kwds:
      selectors: sub_selector_list
      position_map: selector_port_map
      unit_port_count: 11
      passthrough_port: 12
      settle_seconds: 2
  rxn_vessel:
    class: mixology.devices.vessels.SlideContainer
    skip_kwds: [name]
    kwds:
        name: slide_container
        num_slides: 3
  # Full System:
  seqflow:
    class: seqflow.seqflow.SeqFlow
    kwds:
      config: config
      pump: pump
      selector: selector
      rxn_vessel: rxn_vessel
