[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "brainwasher"
version = "0.3.0"
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
   "Pint>=0.21.1",
   "coloredlogs>=15.0.1",
   "pydantic>=2.11.4",
   "datetime>=5.5",
   "pyyaml>=6.0.2",
   "pydantic-settings>=2.12.0",
   "pandas>=2.0.3",
]

[tool.uv.workspace]
members = ["instruments/*"]

[dependency-groups]
dev = [   
    "pytest>=8.3.5",
    "ruff>=0.9.9"
    ]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
