[build-system]
requires = ["uv_build>=0.8.22"]
build-backend = "uv_build"

[project]
name = "mixology"
version = "1.0.0"
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
   "Pint>=0.21.1",
   "coloredlogs>=15.0.1",
   "pydantic>=2.11.4",
   "pyyaml>=6.0.2",
   "pydantic-settings>=2.12.0",
   "pandas>=2.0.3",
   "pyharp>=0.1.0",
   "vicivalve>=0.0.13",
   "rpi-hardware-pwm>=0.3.1",
   "SM16inpind>=1.0.1",
   "SM8mosind>=1.0.1",
   "SM16univin>=1.0.3",
   "smbus2>=0.5.0",
]

[tool.uv.workspace]
members = ["instruments/*"]

[dependency-groups]
dev = [   
    "pytest>=8.3.5",
    "ruff>=0.9.9"
    ]

[tool.pytest.ini_options]
pythonpath = ["src", "tests"]

[tool.uv.sources]
pyharp = { git = "https://github.com/AllenNeuralDynamics/pyharp.git"  }
vicivalve = { git = "https://gitlab.com/Poofjunior/vicivalve.git"}
rpi-hardware-pwm = { git = "https://github.com/Pioreactor/rpi_hardware_pwm.git" }
harp-device-valve-controller = { git = "https://github.com/AllenNeuralDynamics/harp.device.valve-controller.git" }
